RAP_fnc_isPatrolInProgress = {
	["Checking if patrol is initialized (%1)", [RAP_PATROL_INITIALIZED]] call RAP_fnc_debugLog;
	RAP_PATROL_INITIALIZED;
};

RAP_fnc_initializePatrol = {
	["Initializing new patrol"] call RAP_fnc_debugLog;
	RAP_PATROL_INITIALIZED = true;
	[] call RAP_fnc_resetPatrolParams;
	[5] call RAP_fnc_createPatrolGroups;
};

RAP_fnc_createPatrolGroups = {
	params ["_groupCount"];
	
	for [{private _counter = 0}, {_counter < _groupCount}, {_counter = _counter + 1}] do {
		private _newGroup = [
			independent, 
			["I_soldier_F", "I_support_MG_F", "I_Soldier_GL_F", "I_Soldier_M_F", "I_medic_F"], 
			RAP_BASE_CENTER_LOCATION, 
			50, 
			RGG_patrol_obj] call RAP_fnc_createGroup;
		RAP_PATROL_GROUPS pushBackUnique _newGroup;
	}; 
};

RAP_fnc_createGroup = {
	params ["_groupSide", "_units", "_spawnPos", "_area", "_initialOrder"];

	private _pos = [_spawnPos, 20, _area] call BIS_fnc_findSafePos;
	private _newGroup = createGroup _groupSide;
	_newGroup setVariable ["reggsAPSAutoGenerated", true, true];

	private _fireTeam = [];

	{
		private _unit = _newGroup createUnit [_x, _pos, [], 0.1, "none"];
		_fireTeam pushBack _unit;
	} forEach _units;

	["Created new group for %1 with size of %2 and units %3", [_groupSide, count _units, _units]] 
	call RAP_fnc_debugLog;

	if _initialOrder then {
        ["Initial order received: %1", [_initialOrder]] call RAP_fnc_debugLog;
    };

	_newGroup;
};